name = "api-gamification"
main = "src/worker.ts"
compatibility_date = "2024-02-18"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "reading_stats"
database_id = "a7d8da90-3532-40fb-81fc-87fa7432551f"

# Optional: Add KV namespace for rate limiting
# [[kv_namespaces]]
# binding = "RATELIMIT"
# id = "YOUR_KV_NAMESPACE_ID" 

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true






